spring:
  application:
    name: kotlinspringbootweb
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always

